### ISSUE TITLE
SlIM in Arch

### ISSUE THREAD

**Issue by brwadev** [adi1090x/slim_themes#1]
does slim in Arch still working?
i install it but it wont login, can i fix it? your themes just amazing i want to use them

**Comment by adi1090x** [comment]
Yes, it's working in Arch Linux (though i advise you not to use it anymore).
you said it wont login, do you have `.xinitrc`?

**Comment by brwasalam** [comment]
thanks for replay yes i have but it's empty, and i now it was down in 2013 but Do you have any other DM theme like that gorgeous. thanks for your work they are amazing.
