### ISSUE TITLE
Authentication error disappeared

### ISSUE THREAD

**Issue by Evhorizon** [adi1090x/slim_themes#2]
After updating slim to its latest fork 1.4.0 I don't have anymore the "authentication failed" error if I mistype username/password. I contacted the new maintainer of slim and he told me that this error is now disabled by default and we can enable it by appending the following 3 lines to the slim.theme file:
`password_feedback_x     <value>
    password_feedback_y     <value>
    password_feedback_msg   Authentication failed`
I tried with random values and the message is back, if you want you can add these lines to your themes choosing the values that you wish.

**Comment by adi1090x** [comment]
Done, Thanks for the tip.
